### ISSUE TITLE
2016 slide

### ISSUE THREAD

**Issue by haruair** [weirdmeetup/emocon#2]
https://docs.com/justinyoo/5860/azure-functions-serverless

https://docs.com/justinyoo/4247

**Comment by haruair** [comment]
- youtube 영상 받아서 타이틀 붙이고 업로드하기
- 슬라이드랑 같이 아카이브 페이지 만들기

**Comment by minieetea** [comment]
ㅠ_ ㅠ

**Comment by haruair** [comment]
왜왜욬ㅋ

**Comment by minieetea** [comment]
@haruair 네버엔딩태스크 ㅋㅋㅋ

@fra3il 님이 여기다가 정리중이에요. https://drive.google.com/open?id=0B4iE0fhzrpJsZFRBZ2NTTmU3eXc

**Comment by haruair** [comment]
유튜브는 업로드 완료! 아카이브 페이지 만들어야 함.

**Comment by haruair** [comment]
[README.md](https://github.com/weirdmeetup/emocon/tree/gh-pages/2016fw/slides)로 페이지 만들고 [웹](http://emocon.weirdx.io/2016fw/)에 링크 추가했습니다. 드라이브에 있는 슬라이드도 모두 리포지터리에 올렸습니다. 추가/누락된 슬라이드가 있으면 알려주세요. 🐨
